name: .NET

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore OrioksDecorator.sln

    - name: Build
      run: dotnet build --no-restore OrioksDecorator.sln

    - name: Test with dotnet
      run: dotnet test --logger trx OrioksDecorator.sln
